#!/usr/bin/env python3
"Generate pyghostty/_cdef.py from ghostty's libghostty-vt headers. Re-run on each ghostty rev bump and review the diff."
import re,subprocess
from pathlib import Path
from build_lib import ghostty_src

EXCLUDE = {'wasm.h'}  # wasm-only utilities; not part of the native ABI surface

def header_order(inc):
    "All ghostty/vt headers reachable from vt.h, in dependency (include) order."
    seen,out = set(),[]
    def walk(name):
        if name in seen or name.rsplit('/',1)[-1] in EXCLUDE: return
        seen.add(name)
        p = inc/name
        for m in re.findall(r'#include <(ghostty/[\w/]+\.h)>', p.read_text()): walk(m)
        out.append(p)
    walk('ghostty/vt.h')
    return out

def clean(src):
    "One C header's text, reduced to cdef-ready declarations."
    src = re.sub(r'\\\n', ' ', src)  # join line-continued macros so they drop as one line
    src = re.sub(r'#ifdef __cplusplus\nextern "C" \{\n#endif', '', src)
    src = re.sub(r'#ifdef __cplusplus\n\}\n#endif', '', src)
    src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)
    src = re.sub(r'//[^\n]*', '', src)
    src = '\n'.join(l for l in src.splitlines() if not l.lstrip().startswith('#'))
    src = re.sub(r'static inline [^{]*\{[^}]*\}', '', src, flags=re.S)  # header-only helpers: no symbol in the lib
    for macro,repl in [('GHOSTTY_API ',''), ('GHOSTTY_ENUM_TYPED ',''), ('GHOSTTY_ENUM_MAX_VALUE','0x7FFFFFFF')]:
        src = src.replace(macro, repl)
    return re.sub(r'\n{3,}', '\n\n', src).strip()

def gen():
    src = ghostty_src()
    rev = subprocess.run(['git','-C',str(src),'rev-parse','--short','HEAD'], capture_output=True, text=True).stdout.strip()
    parts = [f'/* --- {p.name} --- */\n\n{c}' for p in header_order(src/'include') if (c := clean(p.read_text()))]
    body = '\n\n'.join(parts)
    out = f'"Generated by gen_cdef.py from ghostty {rev}. Do not edit."\n\nCDEF = r\'\'\'\n{body}\n\'\'\'\n'
    dest = Path(__file__).parent/'pyghostty'/'_cdef.py'
    dest.write_text(out)
    print(f'Wrote {dest} from ghostty {rev}: {len(body)} chars')

if __name__=='__main__': gen()
